name: Aggiorna Gist con offerte Xbox

on:
  schedule:
    - cron: "0 6 * * *"  # Ogni giorno alle 6:00 UTC
  workflow_dispatch:     # Avvio manuale

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          python main.py
