name: Aggiorna Gist con uscite giornaliere

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Aggiungi un passo per installare Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Assicurati di avere la versione corretta di Node.js

      # Installa le dipendenze (axios, playwright e altre)
      - name: Install dependencies
        run: |
          npm install

      # Aggiungi un passo per scaricare i browser di Playwright
      - name: Install Playwright browsers
        run: |
          npx playwright install

      # Esegui lo script Node.js
      - name: Run script
        run: node script.js

      # Aggiungi un passo per caricare i dati nel Gist
      - name: Update Gist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"files\": {\"games.json\": {\"content\": \"$(cat games.json)\"}}}" \
            https://api.github.com/gists/$GIST_ID
