name: Aggiorna Gist con uscite giornaliere

on:
  schedule:
    - cron: "0 6 * * *"  # Esegui ogni giorno alle 06:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Step per configurare Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Puoi cambiare la versione di Node.js se necessario

      # Step per installare le dipendenze
      - name: Install dependencies
        run: |
          npm install playwright fs

      # Step per eseguire lo script Node.js
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          node script.js  # Assicurati che il file si chiami "script.js" o modificalo in base al nome che hai dato al file JS
