name: Aggiorna Gist con uscite giornaliere

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installa solo jq per gestire JSON via shell
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Installa le dipendenze Playwright per il sistema
      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      # Installa le dipendenze Node.js del progetto
      - name: Install npm dependencies
        run: npm install

      # Installa i browser di Playwright (Chromium, Firefox, WebKit)
      - name: Install Playwright browsers
        run: npx playwright install

      # Esegui lo script Node.js
      - name: Run script
        run: |
          node script.js || { echo 'Script fallito'; exit 1; }

      # Carica ogni parte in Gist
      - name: Update Gist with game parts
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          for PART in games_part_*.json; do
            echo "Caricamento di $PART su Gist..."
            CONTENT=$(cat $PART)
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"files\":{\"games.json\":{\"content\":$(jq -Rs . < $PART)}}}" \
              "https://api.github.com/gists/$GIST_ID"
          done
