name: Aggiorna Gist con uscite giornaliere

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installa solo jq per gestire JSON via shell
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Installa le dipendenze Playwright per il sistema
      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      # Installa le dipendenze Node.js del progetto
      - name: Install npm dependencies
        run: npm install

      # Installa i browser di Playwright (Chromium, Firefox, WebKit)
      - name: Install Playwright browsers
        run: npx playwright install

      # Esegui lo script Node.js
      - name: Run script
        run: |
          node script.js || { echo 'Script fallito'; exit 1; }

      # Carica ogni parte in Gist
      - name: Update Gist with game parts
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # Unisci tutte le parti in un unico file
          echo "Combinazione dei file in un unico JSON..."
          node -e 'const fs = require("fs"); 
            const parts = fs.readdirSync(".").filter(f => f.startsWith("games_part_"));
            const allGames = [];
            for (const part of parts) {
              const games = JSON.parse(fs.readFileSync(part, "utf8"));
              allGames.push(...games);
            }
            fs.writeFileSync("all_games.json", JSON.stringify(allGames));'
          
          echo "Caricamento del file combinato su Gist..."
          # Crea un file temporaneo per il payload JSON
          echo "{\"files\":{\"games.json\":{\"content\":$(cat all_games.json | jq -Rs .)}}}}" > payload.json
          
          # Usa il file payload per l'aggiornamento di Gist
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            --data @payload.json \
            "https://api.github.com/gists/$GIST_ID"
